import argparse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import glob as glob
import shutil
import pathlib as p
from natsort import natsorted

import pynwb

import spikeinterface as si
import spikeinterface.extractors as se
import spikeinterface.preprocessing as spre
import spikeinterface.sorters as ss
import spikeinterface.postprocessing as spost
import spikeinterface.qualitymetrics as sqm
import spikeinterface.comparison as sc
import spikeinterface.exporters as sexp
import spikeinterface.widgets as sw
import spikeinterface.curation as scur

from probeinterface import Probe, get_probe
from probeinterface.plotting import plot_probe
from probeinterface import generate_linear_probe

from preprocessing.preprocessing_utilities import create_target_folder, change_permissions_recursively

annotation_file = '/mnt/hpc_slurm/departmentN5/mouse-ephys-recordings-log.csv'

base_path = '/mnt/hpc_slurm/projects/OWzeronoise'

def get_grouped_bare_paths(annotation_file, base_path):
    annotation = pd.read_csv(annotation_file)
    annotation['group_ID'] = annotation.groupby(['subject', 'date', 'moved_probe']).ngroup()
    grouped_bare_paths = []

    for group_id in set(annotation['group_ID']):
        group_data = annotation[annotation['group_ID'] == group_id]
        paths = []
        for _, row in group_data.iterrows():
            subject_folder = str(row['subject']).zfill(3)  # Assuming subject is padded with zeros
            session_folder = str(row['session']).zfill(3)  # Assuming session is padded with zeros
            date_str = str(row['date'])
            path = os.path.join(base_path, row['project'], subject_folder, date_str, row['experiment'], session_folder)
            paths.append(path)
        grouped_bare_paths.append(paths)

    return grouped_bare_paths

import os

def filter_grouped_paths(grouped_bare_paths, cronjob_paths):
    """
    Filters the grouped bare paths to include only those paths that have a common base with the normalized cronjob paths.

    :param grouped_bare_paths: List of lists of bare paths generated by get_grouped_bare_paths.
    :param cronjob_paths: List of full paths passed from the cronjob.
    :return: Filtered list of grouped bare paths.
    """
    filtered_grouped_paths = []

    # Normalize cronjob paths to ensure consistency
    normalized_cronjob_paths = [os.path.normpath(path) for path in cronjob_paths]

    for group in grouped_bare_paths:
        # Normalize each path in the group
        normalized_group = [os.path.normpath(path) for path in group]

        # Include the group if any of its normalized paths match the normalized cronjob paths
        if any(path in normalized_cronjob_paths for path in normalized_group):
            filtered_grouped_paths.append(group)

    return filtered_grouped_paths

def collect_nwb_files_and_identifier(bare_paths):
    nwb_paths = [glob.glob(f"{path}/**/*.nwb", recursive=True) for path in bare_paths]
    nwb_paths = sorted(sum(nwb_paths, []), key=lambda session_path: p.Path(session_path).parent.name)
    session_names = [p.Path(path).parent.name for path in nwb_paths]
    identifier = "-".join(session_names)
    return nwb_paths, identifier

def create_sorting_folder(bare_path, identifier):
    # Extract the path up to the date
    parts = bare_path.split(os.sep)
    date_path = os.sep.join(parts[:8])  # Adjust index based on your path structure

    # Construct the sorting folder path
    sorting_folder = os.path.join(date_path, 'sorted-' + identifier)

    # Create the folder if it does not exist
    #if not os.path.isdir(sorting_folder):
    #    os.makedirs(sorting_folder, 0o770, exist_ok=True)
    #    print("Created folder:", sorting_folder)

    return sorting_folder

def load_and_preprocess_recordings(nwb_paths):
    recording_list = []
    for nwb_filename in nwb_paths:
        recording = se.read_nwb(nwb_filename, load_recording=True, load_sorting=False, electrical_series_name='ElectricalSeries_1')
        if recording.get_num_channels() == 8:
            recording = se.read_nwb(nwb_filename, load_recording=True, load_sorting=False, electrical_series_name='ElectricalSeries_2')
        if recording.get_num_channels() == 8:
            raise ValueError(f'Both ElectricalSeries have 8 channels, cannot discriminate raw data for {nwb_filename}')
        
        linear_probe = generate_linear_probe(num_elec=32, ypitch=25, contact_shapes= 'rect', contact_shape_params= {'width': 11, 'height': 15})
        linear_probe.set_contact_ids([18,1,20,3,22,5,23,8,24,7,6,21,4,19,2,17,32,15,30,13,28,11,25,10,26,9,12,27,14,29,16,31])

        nwbio = pynwb.NWBHDF5IO(nwb_filename, "r", load_namespaces=True)
        nwbfile = nwbio.read()

        channels = nwbfile.electrodes['group_name'][:] == 'CH'
        channel_names = nwbfile.electrodes['location'][:][list(channels)]

        if (natsorted(channel_names) == list(channel_names)):
            print("channels are not mapped")
        
            linear_probe.set_device_channel_indices([45,41,43,38,40,35,36,32,31,33,34,42,37,44,39,46,14,22,17,25,18,28,27,30,23,29,26,21,24,19,20,16])

        else:
            print("channels are mapped")
            linear_probe.set_device_channel_indices(np.arange(32))

        ## set the generated probe as the probe used in the recording
        recording = recording.set_probe(linear_probe)

        recording_list.append(recording)
    return recording_list


def perform_spike_sorting(recording_list, sorting_folder):
    
    if len(recording_list) > 1:
        multirecording = si.concatenate_recordings(recording_list)
    else:
        multirecording = recording_list[0]

    multirecording_cmr = multirecording
    
    multirecording_f = spre.bandpass_filter(multirecording, freq_min=300, freq_max=6000)
    
    multirecording_cmr = spre.common_reference(multirecording_f, reference='global', operator='median')
    
    ## now we spikesort using kiloseort 3

    # Perform the sorting
    ss.Kilosort3Sorter.set_kilosort3_path('/mnt/hpc_slurm/departmentN5/external-repos/Kilosort')
    sorting = ss.run_sorter('kilosort3', recording=multirecording_cmr, output_folder=sorting_folder, verbose=True)
    ## remove empty units, messes up stuff later

    sorting = sorting.remove_empty_units()

    ## remove excess spikes
    
    sorting = scur.remove_excess_spikes(sorting, multirecording_cmr)

    ## save the preprocessed recording and motion correction for later use

    preprocessed_folder =  os.path.join(sorting_folder, 'preprocessed-recording')
    
    # this computes and saves the recording after applying the preprocessing chain
    multirecording_cmr.save(format='binary', folder = preprocessed_folder, overwrite = True)

    # Check if the preprocessed recording has been saved
    if not os.path.exists(preprocessed_folder):
        raise FileNotFoundError(f"Preprocessed recording not found in {preprocessed_folder}")

    ## do motion correction and plot drift (only for reference, kilosort does its own motion correction)

    job_kwargs = dict(n_jobs=40, chunk_duration='1s', progress_bar=True)

    recording_corrected, motion_info = spre.correct_motion(multirecording_cmr,
                                                         preset = "kilosort_like",
                                                         folder = os.path.join(sorting_folder, "motion"),
                                                         output_motion_info=True, **job_kwargs)

    ## plot the motion correction

    motion_plot_file = os.path.join(sorting_folder, "motion", 'drift.png')
    
    fig = plt.figure(figsize=(14, 8))
    sw.plot_motion(motion_info, figure=fig,
                   color_amplitude=True, amplitude_cmap='inferno', scatter_decimate=10)
    fig.savefig(motion_plot_file)

    # Check if the motion plot has been saved
    if not os.path.exists(motion_plot_file):
        raise FileNotFoundError(f"Motion plot not found in {motion_plot_file}")

    return sorting, multirecording_cmr


def extract_waveforms_and_compute_metrics(sorting, recording_preprocessed, sorting_folder):
    
    waveforms_folder = os.path.join(sorting_folder, 'waveforms')
    
    waveforms = si.extract_waveforms(recording_preprocessed, sorting, folder=waveforms_folder, overwrite=True, use_relative_path=True, sparse=True)
    
    ## remove redundant units

    sorting = scur.remove_redundant_units(waveforms)

    ## save the clean sorting

    sorting = sorting.save(folder=os.path.join(sorting_folder, 'sorting'))

    ## re-extract waveforms

    waveforms = si.extract_waveforms(recording_preprocessed, sorting, folder = waveforms_folder, overwrite=True, use_relative_path = True, sparse=True)
    
    ## do postprocessing on the waveforms and compute quality metrics
    noise = spost.compute_noise_levels(waveforms)
    amplitudes = spost.compute_spike_amplitudes(waveforms)
    unit_locations = spost.compute_unit_locations(waveforms)
    spike_locations = spost.compute_spike_locations(waveforms)
    correlograms, bins = spost.compute_correlograms(waveforms)
    similarity = spost.compute_template_similarity(waveforms)

    pc = spost.compute_principal_components(waveforms, load_if_exists=True,
                                     n_components=3, mode='by_channel_local')

    qm = sqm.compute_quality_metrics(waveforms)

    return waveforms


def export_and_postprocess_data(waveforms, sorting_folder):
    # Export to Phy
    phy_folder = os.path.join(sorting_folder, 'phy')
    sexp.export_to_phy(waveforms, phy_folder, verbose=True, remove_if_exists=True)

    
    change_permissions_recursively(sorting_folder)
    
    



def run_multisorting(bare_paths):
    nwb_paths, identifier = collect_nwb_files_and_identifier(bare_paths)
    sorting_folder = create_sorting_folder(bare_paths[0], identifier)

    if os.path.isdir(os.path.join(sorting_folder, 'sorting')):
        print("Already sorted, skipping")
        return

    recording_list = load_and_preprocess_recordings(nwb_paths)
    sorting, recording_preprocessed = perform_spike_sorting(recording_list, sorting_folder)
    waveforms = extract_waveforms_and_compute_metrics(sorting, recording_preprocessed, sorting_folder)
    export_and_postprocess_data(waveforms, sorting_folder)


def main(cronjob_paths):
    # Assuming annotation_file and base_path are defined or accessible here
    all_grouped_bare_paths = get_grouped_bare_paths(annotation_file, base_path)

    # Filter them based on the cronjob paths
    filtered_grouped_paths = filter_grouped_paths(all_grouped_bare_paths, cronjob_paths)

    # Process the filtered paths
    for bare_paths in filtered_grouped_paths:
        print("Processing group:", bare_paths)
        run_multisorting(bare_paths)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process paths for multisorting.")
    parser.add_argument('paths', nargs='+', help='Paths to process')
    args = parser.parse_args()

    main(args.paths)
